export {
  isTauri,
  isWeb,
  checkHasVault,
  createVault,
  unlockVault,
  logout,
  checkAuthStatus,
  getAuthToken,
  setAuthToken,
  getEncryptedSessionKey,
  setEncryptedSessionKey,
  getAccounts,
  getAccount,
  createAccount,
  updateAccount,
  deleteAccount,
  searchAccounts,
  getGroups,
  createGroup,
  updateGroup,
  deleteGroup,
  getTags,
  createTag,
  updateTag,
  deleteTag,
  type ApiError,
  type ApiAccount,
  type ApiTag,
  type ApiGroup,
  type CreateAccountPayload,
  type UpdateAccountPayload,
  type AccountSearchParams,
  type CreateGroupPayload,
  type UpdateGroupPayload,
  type CreateTagPayload,
  type UpdateTagPayload,
} from './tauriApi';
